
export const SET_VIDEO_SHOW_LIST = 'SET_VIDEO_SHOW_LIST'
export const SET_VIDEO_SOURCE_LIST = 'SET_VIDEO_SOURCE_LIST'
export const SET_NEXT_VIDEO_LIST_START = 'SET_NEXT_VIDEO_LIST_START'
export const SAVE_SCROLL_POSITION = 'SAVE_SCROLL_POSITION'
